Fix incorrect copy-paste
git-svn-id: svn+ssh://svn.eu.adacore.com/Dev/trunk/gps@162038 936e1b1b-40f2-da11-902a-00137254ae57

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3928,8 +3928,8 @@ fi
      fi
 
      if test x"$WITH_SQLITE" = xno -a x"$NEED_SQLITE" = xyes ; then
-       { { echo "$as_me:$LINENO: error: PostgreSQL not found" >&5
-echo "$as_me: error: PostgreSQL not found" >&2;}
+       { { echo "$as_me:$LINENO: error: Sqlite not found" >&5
+echo "$as_me: error: Sqlite not found" >&2;}
    { (exit 1); exit 1; }; }
      fi
    fi
