Improve detection of gtk+: we also need to check whether we can  find gtkada, since that's needed for the builds. Fixes build  failures when GtkAda was not available on the machine
git-svn-id: svn+ssh://svn.eu/Dev/trunk/gps@126657 936e1b1b-40f2-da11-902a-00137254ae57

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP GNAT_BUILDS_SHARED DEFAULT_LIBRARY_TYPE PKG_CONFIG GTK_GCC_FLAGS WITH_GTK PYTHON PYTHON_BASE PYTHON_VERSION PYTHON_DIR PYTHON_LIBS PYTHON_CFLAGS WITH_PYTHON WITH_POSTGRES PATH_LIBPQ PYGTK_PREFIX PYGTK_INCLUDE WITH_PYGTK PYTHON_LIBS_GPR PYTHON_CFLAGS_GPR PYGTK_INCLUDE_GPR GTK_GCC_FLAGS_GPR WITH_SYSLOG MAKEINFO TEXI2DVI LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP GNAT_BUILDS_SHARED DEFAULT_LIBRARY_TYPE PKG_CONFIG HAVE_GTKADA GTK_GCC_FLAGS WITH_GTK PYTHON PYTHON_BASE PYTHON_VERSION PYTHON_DIR PYTHON_LIBS PYTHON_CFLAGS WITH_PYTHON WITH_POSTGRES PATH_LIBPQ PYGTK_PREFIX PYGTK_INCLUDE WITH_PYGTK PYTHON_LIBS_GPR PYTHON_CFLAGS_GPR PYGTK_INCLUDE_GPR GTK_GCC_FLAGS_GPR WITH_SYSLOG MAKEINFO TEXI2DVI LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3352,7 +3352,42 @@ echo "${ECHO_T}not found" >&6
 echo "${ECHO_T}$GTK_PREFIX" >&6
         GTK_GCC_FLAGS=`$PKG_CONFIG gtk+-2.0 --cflags`
         if test x"$GTK_GCC_FLAGS" != x ; then
-           WITH_GTK=yes
+           echo "$as_me:$LINENO: checking for gtkada" >&5
+echo $ECHO_N "checking for gtkada... $ECHO_C" >&6
+
+   project=gtkada
+   output=HAVE_GTKADA
+
+   # Create a temporary directory (from "info autoconf")
+   : ${TMPDIR=/tmp}
+   {
+     tmp=`(umask 077 && mktemp -d "$TMPDIR/fooXXXXXX") 2>/dev/null` \
+        && test -n "$tmp" && test -d "$tmp"
+   } || {
+     tmp=$TMPDIR/foo$$-$RANDOM
+     (umask 077 && mkdir -p "$tmp")
+   } || exit $?
+
+   mkdir $tmp/lib
+   echo "with \"$project\"; project default is for Source_Dirs use (); end default;" > $tmp/default.gpr
+
+   gnat make -P$tmp/default.gpr >/dev/null 2>/dev/null
+   if test $? = 0 ; then
+     HAVE_GTKADA=yes
+   else
+     HAVE_GTKADA=no
+   fi
+
+
+           if test "$HAVE_GTKADA" = "yes"; then
+              echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6;
+              WITH_GTK=yes
+           else
+              echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+              WITH_GTK=no
+           fi
         else
            WITH_GTK=no
         fi
@@ -4059,6 +4094,8 @@ echo "$as_me:  Shared libraries: $GNAT_BUILDS_SHARED (default: $DEFAULT_LIBRARY_
 echo "$as_me:  Gtk+:   $WITH_GTK" >&6;}
 { echo "$as_me:$LINENO:     Make sure pkg-config is in your PATH" >&5
 echo "$as_me:     Make sure pkg-config is in your PATH" >&6;}
+{ echo "$as_me:$LINENO:     and gtkada.gpr in your project path" >&5
+echo "$as_me:     and gtkada.gpr in your project path" >&6;}
 { echo "$as_me:$LINENO:  Python: $WITH_PYTHON $PYTHON_BASE" >&5
 echo "$as_me:  Python: $WITH_PYTHON $PYTHON_BASE" >&6;}
 { echo "$as_me:$LINENO:     use --with-python to override" >&5
@@ -4747,6 +4784,7 @@ s,@EGREP@,$EGREP,;t t
 s,@GNAT_BUILDS_SHARED@,$GNAT_BUILDS_SHARED,;t t
 s,@DEFAULT_LIBRARY_TYPE@,$DEFAULT_LIBRARY_TYPE,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
+s,@HAVE_GTKADA@,$HAVE_GTKADA,;t t
 s,@GTK_GCC_FLAGS@,$GTK_GCC_FLAGS,;t t
 s,@WITH_GTK@,$WITH_GTK,;t t
 s,@PYTHON@,$PYTHON,;t t
